- .github/workflows/call-e2e.yaml
空格缩进有问题导致 github action 解析失败，忽略 CodeFactor — 3 issues found. 的提示，当初就是因为它，我把缩进给去掉了。
> Fix the spacing issue in gitHub actions config

- .github/workflows/auto-nightly-ci.yaml
**What this PR does / why we need it**:
Modify the label used for CI failures，corrected kind/bug to kind/ci-bug
**make sure your commit is signed off**
Signed-off-by: ty-dc [tao.yang@daocloud.io](mailto:tao.yang@daocloud.io)
> Modify the label used for CI failures

- charts/templates/tls.yaml
Fix https://github.com/spidernet-io/egressgateway/issues/414
> Fix webhook definition has no file delimiter symbol

- pkg/agent/vxlan/vxlan.go
Fix https://github.com/spidernet-io/egressgateway/issues/450
> Fix data race check of vxlan

- pkg/agent/police.go
减少用户使用的使用 `EgressPolicy` 的复杂度，可以不配置 `destSubnet` 字段。这时将对 `EgressPolicy` 匹配中的 Pod 除了访问集群内部网络地址的流量转发的出口网关。
将 egress-controller 收集的集群内部子网信息记录到名为 `egress-cluster-cidr-ipv4` 和 `egress-cluster-cidr-ipv6` 的 ipset。此 PR 增加「EgressPolicy 未定义 destSubnet 时对除了 internal CIDR 的流量进行 egress 转换」的 datapath 逻辑。
> Add datapath logic for ignore internal CIDR

- pkg/agent/eip.go
修复供 arp 宣告的日志模块 level 不一致问题
```json
{
"level":"ERROR",                                              # 1
"ts":"2023-06-29T08:26:24.495Z",
"logger":"layer2",
"caller":"agent/eip.go:129",
"msg":"created NDP responder for interface",
"level":"info",                                               # 2
"interface":"calicc4b5600da7",
"event":"createNDPResponder"
}
```
> Fix log wrapper

- pkg/agent/vxlan/vxlan.go
IPv6 不使用 rp_filter，ipv6 使用 [SAVI](https://www.rfc-editor.org/rfc/rfc7039.html)，我们在这个 PR 中停止对 IPv6 设置 rp_filter。前面我验证过 Egress IPv6 通讯正常，如果存在问题，我们会在另外的 PR 中解决。
> Fix IPv6 does not support rp_filter

- pkg/agent/police.go
- pkg/utils/flat.go
如果 ns 为空，不使用 path.Join 去 join namespace 的值，它会导致我们在 namespace 的字段上得到一个 kind 类型的值，预期是 kind/namespace
> Fix path join empty will not add ''/'

- docs/concepts/Architecture.en.md
- docs/concepts/Architecture.zh.md
- docs/crds/EgressClusterInfo.en.md
- docs/crds/EgressClusterInfo.zh.md
- docs/crds/EgressGateway.zh.md
- docs/crds/EgressNode.en.md
- docs/crds/EgressNode.zh.md
* 我们在文档站二级菜单 CRD 下，仅介绍了 CRD 字段的定义以及使用场景。与 CRD 有关底层代码逻辑都移动到 架构 或 开发 的二级目录下。
* 增加中英文文档
* 优化标点，拼写，句子
> Update crd docs

- test/Makefile
Add more logs, let's see why the github action has the following output, and there is no such output local env:
```
/etc/bash.bashrc: line 7: PS1: unbound variable
/etc/bash.bashrc: line 7: PS1: unbound variable
/etc/bash.bashrc: line 7: PS1: unbound variable
/etc/bash.bashrc: line 7: PS1: unbound variable
/etc/bash.bashrc: line 7: PS1: unbound variable
/etc/bash.bashrc: line 7: PS1: unbound variable
/etc/bash.bashrc: line 7: PS1: unbound variable
/etc/bash.bashrc: line 7: PS1: unbound variable
```
> Add ouput log for test

- charts/README.md
- charts/values.yaml
- pkg/agent/eip.go
- pkg/agent/police.go
- pkg/config/config.go
支持通过 announcedInterfacesToExclude 屏蔽不需要 arp 回复的网卡(解决 https://github.com/spidernet-io/egressgateway/pull/566 测试出的问题)
减少 cluster internal cidr ipset 函数的复杂度
> Add `announcedInterfacesToExclude` configurations

- cmd/nettools/initFlag.go
每次运行的时候打印 usage 导致 e2e 日志太过冗长。查看用法使用 `tools --help` 即可。
> Remove the usage output when running nettools

- .github/workflows/auto-pr-ci.yaml
ubuntu 20.04 with kind is not compatible with k8s 1.23.*+ (excluding `1.23.*`).
Fix:
https://github.com/spidernet-io/egressgateway/issues/627
https://github.com/spidernet-io/egressgateway/issues/625
https://github.com/spidernet-io/egressgateway/issues/602
> Fix nightly ci

- test/e2e/common/egressclusterinfo.go
- test/e2e/egressclusterinfo/egressclusterinfo_suite_test.go
- test/e2e/egressclusterinfo/egressclusterinfo_test.go
> cancel egci test case

- .github/codespell-ignorewords
- charts/crds/egressgateway.spidernet.io_egressgateways.yaml
- charts/templates/tls.yaml
- docs/mkdocs.yml
- docs/usage/ClusterDefaultEgressGateway.en.md
- docs/usage/ClusterDefaultEgressGateway.zh.md
- docs/usage/Install.en.md
- docs/usage/Install.zh.md
- docs/usage/NamespaceDefaultEgressGateway.en.md
- docs/usage/NamespaceDefaultEgressGateway.zh.md
- go.mod
- pkg/controller/controller.go
- pkg/controller/webhook/mutating.go
- pkg/controller/webhook/validate.go
- pkg/egressgateway/egress_gateway_webhook.go
- pkg/k8s/apis/v1beta1/egressgateway_types.go
- pkg/k8s/apis/v1beta1/labels.go
- test/doc/egressgateway_zh.md
- test/e2e/egressgateway/default_egressgateway_test.go
为了设定租户级的默认网关，可以在 Namespace 上打上特定的标签 `spidernet.io/egressgateway-default` 设置默认网关的名称。
1. 使用以下命令为命名空间设置默认网关标签：
```shell
kubectl label ns <namespace> spidernet.io/egressgateway-default=<egress-gateway-name>
```
其中，`<namespace>` 是目标命名空间，`<egress-gateway-name>` 是要设定为默认网关的 EgressGateway 的名称。
在集群级别上，思考了 3 个方案，目前使用选项 1 实现。
```diff
type EgressGatewaySpec struct {
+	// +kubebuilder:validation:Optional
+	ClusterDefault bool `json:"clusterDefault,omitempty"`
// +kubebuilder:validation:Optional
Ippools Ippools `json:"ippools,omitempty"`
// +kubebuilder:validation:Required
NodeSelector NodeSelector `json:"nodeSelector,omitempty"`
}
```
将一个名为 `default` 的 EgressGateway 作为集群的默认网关。唯一性好。
通过给特定的 EgressGateway 打上标签 `spidernet.io/egressgateway-cluster-default=true`，来指定该 EgressGateway 为集群级别的默认网关。
1. 为目标 …
> Add default egw

- pkg/agent/route/route.go
- pkg/agent/vxlan.go
ref https://github.com/spidernet-io/egressgateway/issues/654
仅下发必要的路由，否则再用 1000 个节点时，会下发 1000 条路由，会占用不必要的主机资源。
```log
0:	from all lookup local
5203:	from all fwmark 0x26005d90 lookup 637558160
32766:	from all lookup main
32767:	from all lookup default
```
> Reduce unnecessary routes

- pkg/agent/eip.go
- pkg/agent/police.go
- pkg/controller/cluster_endpoint_slice.go
- pkg/controller/egress_policy.go
- pkg/controller/egress_tunnel.go
- pkg/controller/endpoint_slice.go
- pkg/egressgateway/egress_gateway.go
Fix https://github.com/spidernet-io/egressgateway/issues/656
controller:
* 这些信息是比较重要的，做一些合并，减少日志量；
*  周期日志问题：kubelet 的 Node 的更新事件触发的，调整了日志级别；
agent:
* 周期日志问题：这个是 agent 定期维护 policy 规则，防止保第三方用户误删，是 debug 级别的。
> optimize log output

- pkg/controller/webhook/validate.go
- pkg/controller/webhook/validate_test.go
- test/e2e/common/eci.go
修复 由于 Spec.AppliedTo.PodSelector 为 nil 时，创建 policy ， controller panic
相关issue: #868
> Fix panic due to nil spec.appliedTo.podSelector in policy

- go.mod
- test/e2e/common/egp.go
- test/e2e/egressgateway/egressgateway_test.go
- test/e2e/egresspolicy/egresspolicy_test.go
添加 e2e 用例： P00001 P00004 P00005 P00006 P00017
这些用例主要是测试创建 policy 和 cluster-policy 时的一些限定校验是否符合预期，主要包含了如下校验：
1. 使用不合法的 egressIP 创建 policy 会失败
2. 当手动指定的 policy 的 egressIP 没有在这个 policy 所使用的 gateway 的 IP 池范围内时，会创建失败
3. 当 policy 的 Spec.AppliedTo 为空时 会创建失败
4. 当 policy 同时指定了 Spec.AppliedTo.PodSubnet 和 Spec.AppliedTo.PodSelector 时，会创建失败
5. 当 policy 的 Spec.EgressIP.UseNodeIP 为 true，但是同时又指定了 egressIP 时，会创建失败
> Add e2e case P00001 P00004 P00005 P00006 P00017

- test/e2e/egressgateway/egressgateway_test.go
- test/e2e/egresspolicy/egresspolicy_suite_test.go
- test/e2e/egresspolicy/egresspolicy_test.go
- test/e2e/reliability/reliability_ip_test.go
添加 e2e 用例 P00015 P00016
此用例测试在创建policy时,EgressIP.UseNodeIP设置为true的情况下,更新gateway后的一些校验。用例步骤如下:
1. 创建gateway,指定nodeSelector为node1
2. 创建policy,设置EgressIP.UseNodeIP为true
3. 校验gateway和policy状态,校验pod的出口ip应该为node1的IP
4. 更新gateway,使其从匹配node1更新为匹配node2
5. 校验gateway和policy状态,校验pod的出口ip应该为node2的IP
> add e2e case P00015 and P00016

- test/e2e/egressgateway/egressgateway_test.go
G00014：测试编辑 egressGatewaySpec.NodeSelector 以及检查网关、策略和pod的出口IP的同步状态
用例思路：
1. 创建一个 egressGateway，指定 NodeSelector 为 node1，创建 policy、cluster-policy 和 daemonset
2. 将 egressGatewaySpec.NodeSelector 从 node1 更新为 node2，检查 gateway、policy 和 cluster-policy 的状态,，检查 pod 的出口 IP
3. 将 egressGatewaySpec.NodeSelector 从 node2 新为不匹配任何节点，检查gateway、policy 和 cluster-policy 的状态，检查pod 的出口 IP
4. 将 egressGatewaySpec.NodeSelector 从不匹配任何节点重新更新为 node2，检查gateway、policy 和 cluster-policy 的状态，检查 pod 的出口 IP
> Add e2e case G00014: edit the egressGatewaySpec.NodeSelector

- .github/workflows/call-lint-chart.yaml
Fix https://github.com/spidernet-io/egressgateway/issues/907
Ref https://github.com/helm/chart-testing-action/issues/132
是 100% 失败，需要升级版本
> Update chart-testing-action to v2.6.0

- pkg/controller/egress_cluster_info/egress_cluster_info.go
- pkg/controller/egress_cluster_info/egress_cluster_info_internal_test.go
简化 检测 calico 是否存在的逻辑，优化代码
之前根据 channel 来决定是否需要关闭 检测 calico 是否存在的协程
目前改为 通过 原子变量 的方式判断
修复：#851
> Optimize the code for checking whether Calico exists

- test/e2e/common/egp.go
修复 test/e2e/common/egp.go 中 WaitEgressPolicyStatusReady 判断 policy status 的 bug
> Fix the policy's status check in the function  in the e2e test

- pkg/egressgateway/egress_gateway.go
主要解决 egw 分配、回收 IP 的问题，对应了多个 issue ：
fix: https://github.com/spidernet-io/egressgateway/issues/846
fix: https://github.com/spidernet-io/egressgateway/issues/832
fix: https://github.com/spidernet-io/egressgateway/issues/811
fix: https://github.com/spidernet-io/egressgateway/issues/475
> fix: egw status update failed

- test/e2e/common/pod.go
- test/e2e/egresspolicy/egresspolicy_test.go
命名空间级别的 policy 作用域 只作在 其指定的 namespace 中生效
1. 创建 ns test-ns
2. 在 default， test-ns 命名空间中分别创建同名 pod
3. 在 default 命名空间 创建 policy， PodSelector 对应以上 pod 的 label
4. 检测 default 命名空间中的 pod 出口 IP 应该为 policy 的 eip
5. 检测 test-ns 命名空间中的 pod 出口 IP 不应为 policy 的 eip
> Add case P00021

- pkg/controller/webhook/validate.go
- test/e2e/egresspolicy/egresspolicy_test.go
校验 policy 的 Spec.EgressIP.IPv6 及 Spec.EgressIP.IPv4 格式
Fix: #872
> Fix the validation of the policy's EIP format

- pkg/controller/webhook/validate.go
- pkg/controller/webhook/validate_test.go
- test/e2e/egresspolicy/egresspolicy_test.go
修复 创建 policy 或者 clusterPolicy 的时候，PodSubnet 和 PodSelector 都为空的时候，创建成功的问题。
我们期望是不能够创建成功的
Fix: #873
> Fix the validation of the policy's PodSubnet and PodSelector

- charts/crds/egressgateway.spidernet.io_egresstunnels.yaml
- docs/reference/EgressTunnel.en.md
- docs/reference/EgressTunnel.zh.md
- pkg/agent/vxlan.go
- pkg/controller/egress_tunnel.go
- pkg/k8s/apis/v1beta1/egresstunnel_types.go
Fix https://github.com/spidernet-io/egressgateway/issues/953
If the heartbeat logic of the egressgateway is not enabled, we will synchronize the health status of the nodes and switch the eip based on this status. If it is enabled, the switch will be made based on the heartbeat status reported by the agent.
如果未启动 egressgateway 的心跳逻辑，我们将同步 node 节点的健康状况，并根据此状况进行 eip 切换。若已启动，则会根据 agent 报告的心跳状态进行切换。
> sync node status to egt

- pkg/controller/webhook/validate.go
- pkg/controller/webhook/validate_test.go
- pkg/egressgateway/egress_gateway.go
- pkg/egressgateway/egress_gateway_webhook.go
- pkg/utils/ip/ip.go
- pkg/utils/ip/ip_test.go
- test/e2e/egresspolicy/egresspolicy_test.go
Fix: #871 
Fix: #1017
This pr fixed the two issues below:
1. Verify that the Egress IP (EIP) falls within the IP address range configured in the IP pools of the Egress Gateway when creating the Egress Policy.
2. Allow the creation of a single IPv4 or IPv6 IP pool when the Egress Gateway ConfigMap is set to dual mode.
> Verify that the EIP within the IP address ranges configured in the ippools of the egressgateway

- test/doc/egressendpointslice.md
- test/doc/egressendpointslice_zh.md
- test/e2e/common/check_eip.go
- test/e2e/common/deploy.go
- test/e2e/common/egep.go
- test/e2e/common/egp.go
- test/e2e/common/pod.go
- test/e2e/egressendpointslice/egressendpointslice_suite_test.go
- test/e2e/egressendpointslice/egressendpointslice_test.go
- test/e2e/tools/tools.go
Fix #927
Testing the impact of adding and deleting Pods on EndpointSlices and Pod egress IP.
1. Create a gateway.
2. Create a policy.
3. Create and delete 10 Pods.
4. Verify the status of EndpointSlices and the egress IP of Pods.
5. When deleting all Pods, EndpointSlices should be deleted as well.
> Add e2e case S00001

- test/e2e/common/egp.go
- test/e2e/egressendpointslice/egressendpointslice_test.go
- test/e2e/egressgateway/egressgateway_test.go
- test/e2e/egresspolicy/egresspolicy_test.go
- test/e2e/reliability/reliability_test.go
- test about default gateway
1. When creating a cluster-level policy without specifying a gatewayName, it will use the cluster's default gateway if it exists.
2. When creating a namespace-level policy without specifying a gatewayName, it will use the namespace's default gateway or the cluster's default gateway. If both default gateways exist, the policy will use the namespace-level default gateway.
- open some test case
> Add the test case P00002 about default gateway

- test/e2e/common/ds.go
- test/e2e/common/pod.go
- test/e2e/egressendpointslice/egressendpointslice_test.go
- test/e2e/egressgateway/egressgateway_test.go
- test/e2e/egresspolicy/egresspolicy_test.go
- test/e2e/reliability/reliability_ip_test.go
- test/e2e/reliability/reliability_test.go
Fix #1108, increase the time to wait policy status to be synced
Fix #1109, add retry in function DeletePodsUntilReady in the file test/e2e/common/pod.go
Fix #1110, ensure the container runing when check the egressIP of the pod
Fix #1111, increase the time to wait egressendpointslice to be deleted
Fix #1126, increase the time to wait daemonset created
> E2E: enhance the test cases stability

- pkg/egressgateway/egress_gateway_webhook.go
Fix https://github.com/spidernet-io/egressgateway/issues/839
Fix https://github.com/spidernet-io/egressgateway/issues/538
can create egressgateway ippools IP repeat 
cannot create egressgateway ippools IP repeat
> Update EgressGateway validation

- pkg/egressgateway/egress_gateway_webhook.go
When comparing with the cluster's IP pool, one should not include oneself.
Fix https://github.com/spidernet-io/egressgateway/issues/1155
Fix https://github.com/spidernet-io/egressgateway/issues/1158
> Fix: failed to update IP address of egw

- pkg/agent/route/route_test.go
- pkg/agent/vxlan/vxlan_test.go
- pkg/config/config_test.go
- pkg/controller/egress_cluster_info/egress_cluster_info_test.go
- pkg/controller/endpoint/cluster_endpoint_slice_test.go
- pkg/controller/endpoint/endpoint_slice_test.go
- pkg/markallocator/allocator_test.go
Fix #1194
```
Failed to combine cover profiles
Unable to read coverage file /home/runner/work/egressgateway/egressgateway/pkg/controller/egress_cluster_info/coverage.out.3:
open /home/runner/work/egressgateway/egressgateway/pkg/controller/egress_cluster_info/coverage.out.3: no such file or directory
```
> fix 'Failed to combine cover profiles'

- .github/workflows/call-e2e.yaml
- Makefile
- test/Makefile
> Add clean egress

- pkg/controller/tunnel/egress_tunnel.go
- pkg/controller/tunnel/egress_tunnel_test.go
- pkg/egressgateway/egress_gateway.go
- pkg/utils/finalizers.go
- pkg/utils/finalizers_test.go
Fix RemoveFinalizers to improve code reusability
> Fix RemoveFinalizers to improve code reusability

- .github/workflows/call-release-image.yaml
Fix create release get error:
```
main.go:74: error during command execution: signing [ghcr.io/spidernet-io/egressgateway-nettools@sha256:745978f4eea7422480fc6f5bdf1e97bbd04463a90963c245c0b67b7e570fff7a]: getting signer: getting key from Fulcio: getting CTFE public keys: updating local metadata and targets: error updating to TUF remote mirror: invalid key
```
ref https://github.com/sigstore/cosign/issues/3614
> Update cosign to v2.2.3

- cmd/nettools/client/batch/batch.go
- test/Makefile
- test/scripts/check-nettools-server.sh
Fix https://github.com/spidernet-io/egressgateway/issues/1215
Fix https://github.com/spidernet-io/egressgateway/issues/1300
Fix https://github.com/spidernet-io/egressgateway/issues/1304
This is a script that runs before the start of e2e tests; failures in this script have affected the nightly e2e runs. Refactored this shell script to increase its robustness.
> Fix check net tool server process

- test/Makefile
- test/e2e/common/ds.go
- test/e2e/common/egw.go
- test/e2e/common/log.go
- test/e2e/egressgateway/egressgateway_test.go
- test/e2e/egresspolicy/egresspolicy_test.go
- test/e2e/reliability/reliability_test.go
When egresss e2e, daemonset will be started for testing. The startup timeout was originally set to 30s. I observed that it does start slowly. I adjusted the timeout and added a detailed debug log.
> enhance e2e for restart api-server case

- .github/workflows/auto-release.yaml
- .github/workflows/build-image-base.yaml
- .github/workflows/call-e2e.yaml
- .github/workflows/call-release-changelog.yaml
- .github/workflows/call-release-chart.yaml
- .github/workflows/call-release-image.yaml
- .github/workflows/call-release-pages.yaml
- .github/workflows/call-trivy.yaml
- .github/workflows/helm.yml
- .github/workflows/lint-golang.yaml
- .github/workflows/lint-yaml.yaml
Fix CI faild:
https://github.com/spidernet-io/egressgateway/issues/1405
https://github.com/spidernet-io/egressgateway/issues/1403
upload-artifact v4 download all 有兼容性问题，如果 name 字段未填写，意思为下载所有 artifact，观察 👀 到如果 artifact 中包含一个 tar 包的附件，download all 就会出现问题，v3 不会出现问题，但 v3 过几个月就废弃。
> Bump actions/upload-artifact to v4.3.4

- docs/usage/AwsWithCilium.en.md
- docs/usage/AwsWithCilium.zh.md
- pkg/agent/police.go
- pkg/agent/vxlan/parent.go
- pkg/controller/clusterinfo/clusterinfo.go
- pkg/controller/clusterinfo/k8sservice.go
Fix https://github.com/spidernet-io/egressgateway/issues/1424
Fix detect vxlan parent IP logic not skip IP addresses with a full subnet mask (e.g., /32 for IPv4 and /128 for IPv6).
On AWS, when main network card has multiple IP, and it is set to default route.
```go
if ones == 32 && bits == 32 || ones == 128 && bits == 128 {
continue
}
```
Add more iptabels accept rule skip cilium rule.
Add **kube-controller-manager** labels case, We use these labels to retrieve the kube-controller-manager Pod arguments in order to obtain the cluster CIDR. Since different clusters have different kube-controller-manager labels, the content of the labels also varies.
If not found CalicoIPPool CRD in current cluster, skipping watch CalicoIPPool.
> Fix run on aws ec2 with cilium

- cmd/agent/cmd/root.go
- cmd/controller/cmd/root.go
when k8s deletes a pod, it sends a `sigterm` signal.
> fix: add sigterm signal

- .github/workflows/call-trivy.yaml
ref:
https://github.com/aquasecurity/trivy-action/issues/389
fix:
https://github.com/spidernet-io/egressgateway/issues/1546
reason:
The rate limiting is for the downloads from the GitHub container registry. As a solution, this PR adds the public ECR registry as a fallback option when the rate limit hits with the GitHub container registry.
> Fix `TOOMANYREQUESTS` failure in Trivy Action

- charts/templates/egressClusterInfo.yaml
Otherwise it's not possible to deploy multiple cidrs via Flux.
> fix: correctly generate an array for egress cluster info with extra cidrs

- pkg/agent/agent.go
- pkg/agent/vxlan.go
- pkg/config/config.go
- pkg/controller/endpoint/endpoint_slice.go
This PR removes an unnecessary watch event, significantly reducing log output.
Fix https://github.com/spidernet-io/egressgateway/issues/1491
> Reduce egress gateway agent event

- test/scripts/installCalico.sh
Fix https://github.com/spidernet-io/egressgateway/issues/1708
Fix `x-kubernetes-validations` unsupported in older Kubernetes versions
> Fix x-kubernetes-validations unsupported in older Kubernetes versions
