spidernet-io/egressgateway

test/Makefile
test/scripts/debugCluster.sh

ci: print env

---

.github/workflows/auto-ci.yaml
.github/workflows/call-e2e.yaml
.github/workflows/call-trivy.yaml

workflow: accelerate all ip family

---

.github/workflows/auto-nightly-ci.yaml
.github/workflows/auto-pr-ci.yaml

ci: nightly

---

images/agent-base/Dockerfile
images/agent/Dockerfile
images/controller-base/Dockerfile
images/controller/Dockerfile

fix: arm64

---

images/agent/Dockerfile
images/controller/Dockerfile

base os tag

---

.github/workflows/auto-cherrypick.yaml
.github/workflows/auto-release.yaml

ci: cherry pick

---

.github/workflows/auto-cherrypick.yaml
.github/workflows/pr-label-check.yaml

ci: check label

---

.github/workflows/auto-cherrypick.yaml
.github/workflows/pr-label-check.yaml

workflow: fix label check

---

pkg/k8s/client/clientset/versioned/clientset.go
pkg/k8s/client/informers/externalversions/factory.go

Fix Night CI Failed https://github.com/spidernet-io/egressgateway/issues/90

Update CRD SDK

---

.github/workflows/auto-cherrypick.yaml

ci: pr title of cherry pick

---

.github/workflows/lint-golang.yaml

check sdk when updating vendor

---

.github/workflows/build-image-base.yaml
.github/workflows/call-release-image.yaml
Makefile
charts/values.yaml
images/agent/Dockerfile
images/controller/Dockerfile

change image name

---

pkg/agent/police.go
pkg/agent/route/route.go
pkg/agent/vxlan.go
pkg/agent/vxlan_test.go
pkg/controller/egress_gateway.go
pkg/controller/egress_gateway_test.go
pkg/utils/node.go

Implement egress gateway node agent, for more info ref [proposal](https://github.com/spidernet-io/egressgateway/tree/main/docs/proposal/01-egress-gateway), the first controller in the picture.
Reconcile EgressGateway for first controller:
* Add/Update/Delete EgressGateway
* Sync route
Test case:
* Add later

Support Route

---

pkg/agent/police.go

* Fix reconcile egress gateway
* apply iptables
* Add more debug logs

Fix reconcile egress gateway

---

go.mod
go.sum
pkg/controller/controller.go
pkg/controller/egress_node.go
pkg/ipam/ipam.go
vendor/github.com/cilium/ipam/LICENSE
vendor/github.com/cilium/ipam/service/allocator/BUILD
vendor/github.com/cilium/ipam/service/allocator/bitmap.go
vendor/github.com/cilium/ipam/service/allocator/interfaces.go
vendor/github.com/cilium/ipam/service/allocator/utils.go
vendor/github.com/cilium/ipam/service/ipallocator/BUILD
vendor/github.com/cilium/ipam/service/ipallocator/allocator.go
vendor/modules.txt

Signed-off-by: dcwbq <biqiang.wu@daocloud.io>

Implement the EgressNode controller

---

charts/values.yaml
pkg/agent/police.go
pkg/agent/police_test.go
pkg/agent/vxlan.go
pkg/agent/vxlan/vxlan.go
pkg/agent/vxlan_test.go

* fix IPv4 condition `if status.VxlanIPv4IP == "" && r.cfg.FileConfig.EnableIPv4 {`
* fix e2e

Fix IPv4 condition

---

charts/templates/configmap.yaml
pkg/agent/route/route.go
pkg/agent/vxlan.go
pkg/agent/vxlan_test.go

Fix https://github.com/spidernet-io/egressgateway/issues/163

Fix multi route

---

.github/workflows/update-chart-readme.yml
charts/README.md
charts/templates/configmap.yaml
charts/templates/daemonset.yaml
charts/templates/deployment.yaml
charts/values.yaml

* Add github action for helm chart README.md generate
* Update iptables settting 
* Fix https://github.com/spidernet-io/egressgateway/issues/195

Update helm chart

---

pkg/controller/egress_gateway.go

Fix https://github.com/spidernet-io/egressgateway/issues/211

Fixed the issue where EgressGateway creation preceded node labeling.

---

pkg/k8s/apis/egressgateway.spidernet.io/v1/egressgatewaynode_types.go

Fix https://github.com/spidernet-io/egressgateway/issues/221

Avoid null value when serializing operations

---

.github/workflows/build-image-base.yaml
.github/workflows/call-release-image.yaml

Fix https://github.com/spidernet-io/egressgateway/issues/234

Update docker login action

---

.github/workflows/badge.yaml
README.md
test/doc/egressgateway.md
test/doc/egressnode.md
test/doc/egresspolicy.md
test/doc/stress.md
tools/golang/e2ecover.sh

add e2e doc and e2e cover badge

add e2e doc and badge

---

.github/workflows/call-e2e.yaml

Fix e2e render variables

---

pkg/agent/police.go
pkg/agent/police_test.go

Fix https://github.com/spidernet-io/egressgateway/issues/243

Update iptables rule match criteria

---

test/e2e/common/egressgateway.go
test/e2e/common/egressnode.go
test/e2e/common/node.go
test/e2e/egressgateway/egressgateway_suite_test.go
test/e2e/egressgateway/egressgateway_test.go
test/e2e/egressnode/egressnode_suite_test.go
test/e2e/egressnode/egressnode_test.go

opened some pending cases about egressgateway and egressnode：
G00001 G00002 G00003 N00001

opened some pending cases about egressgateway and egressnode

---

.github/workflows/call-e2e.yaml
test/e2e/egressgateway/egressgateway_test.go
test/e2e/egressnode/egressnode_test.go
test/e2e/egresspolicy/egresspolicy_test.go

pending e2e case

---

.github/workflows/call-e2e.yaml

pending e2e

---

charts/templates/tls.yaml
charts/values.yaml
pkg/controller/egress_cluster_info.go
pkg/controller/webhook/validate.go

add webhook about delete egressClusterInfo

add webhook about delete egressClusterInfo

---

.github/workflows/call-e2e.yaml

open the call-e2e ci yaml

---

charts/templates/role.yaml
pkg/k8s/apis/egressgateway.spidernet.io/v1beta1/rbac.go

Fix https://github.com/spidernet-io/egressgateway/issues/344

Fix authorization error watching 

---

.github/workflows/call-release-changelog.yaml
.github/workflows/call-release-pages.yaml

Fix https://github.com/spidernet-io/egressgateway/issues/384

Fix github action

---

README.md

https://bestpractices.coreinfrastructure.org/zh-CN/projects/7410

Add badges of OpenSSF

---

test/doc/egressgateway.md
test/doc/egressnode.md
test/doc/egresspolicy.md
test/e2e/egressgateway/egressgateway_test.go
test/e2e/egressnode/egressnode_test.go
test/e2e/egresspolicy/egresspolicy_test.go

Delete invalid use cases

---

.github/workflows/update-golang-version.yaml
Makefile
Makefile.defs

Fix https://github.com/spidernet-io/egressgateway/issues/442

Update "golang auto upgrade" workflow

---

pkg/agent/vxlan/vxlan.go

Fix: https://github.com/spidernet-io/egressgateway/issues/486
```
/# curl 172.18.0.1:8080
Remote IP: 172.18.0.12:58322
```

Update rp_filter settting of vxlan

---

docs/README.zh.md
docs/mkdocs.yml
docs/usage/Install.en.md
docs/usage/Install.zh.md

* 支持代码高亮
* 支持点击代码注释展开提示
* 增加安装的中文文档

Update installation docs

---

test/Makefile
test/e2e/common/constant.go
test/e2e/common/deployment.go
test/e2e/common/egressconfigmap.go

fix e2e get egressgateway configmap error #485

fix e2e fialed get egressgateway configmap

---

tools/golang/e2ecover.sh

fix e2e cover

---

pkg/agent/eip.go
pkg/agent/police.go
pkg/controller/endpoint_slice.go

修复扩容 deploy 副本时更新 ep slice 漏掉一个 Pod

Fix update endpoint slice

---

pkg/controller/egress_node.go

Fix: https://github.com/spidernet-io/egressgateway/issues/520

Fix rebuild cache

---

.github/workflows/auto-cherrypick.yaml

Fix https://github.com/spidernet-io/egressgateway/actions/runs/5420751076/jobs/9855297310

Fix auto cherry pick workflow

---

docs/usage/Uninstall.en.md
docs/usage/Uninstall.zh.md

Add uninstall docs

---

.github/workflows/call-e2e.yaml

Fix https://github.com/spidernet-io/egressgateway/issues/541
```
Unexpected input(s) 'id', valid inputs are ['go-version', 'go-version-file', 'check-latest', 'token', 'cache', 'cache-dependency-path', 'architecture']
```

Remove id field in setup go steps

---

pkg/egressgateway/egress_gateway.go

https://github.com/spidernet-io/egressgateway/pull/428 e2e 任务受这个问题阻碍，所以优先修复下这个问题

Fix delete policy not update gateway status

---

.github/workflows/lint-golang.yaml

Fix https://github.com/spidernet-io/egressgateway/issues/546

Remove swagger SDK check of workflow

---

.github/workflows/auto-cherrypick.yaml

Fix https://github.com/spidernet-io/egressgateway/issues/551

Add support for 'squash and merge'

---

pkg/agent/police.go

Add clean ipset function

---

CODEOWNERS

The api folder has been removed, modify the owners file synchronously

Update owners file

---

charts/templates/tls.yaml

delete `create` `update` about tls for egressclusterinfos

update tls for egressclusterinfos

---

charts/templates/deployment.yaml
pkg/agent/eip.go
pkg/config/config.go
pkg/logger/logger.go

eip 原先这个判断导致 IPv6 单栈不会工作，同时修复了下日志模块
```go
if ip.To4() == nil {
continue
```

Fix egress ip not work for ipv6

---

pkg/ipset/ipset.go

Add ipset output logging

---

test/Makefile

Fix https://github.com/spidernet-io/egressgateway/issues/563

Fix load nettools image

---

test/e2e/common/constant.go
test/e2e/common/eip.go
test/e2e/egresspolicy/egresspolicy_test.go

fix tcp reset by peer when e2e check eip
#570

fix tcp reset by peer

---

test/e2e/common/eip.go

add kill exec process

---

test/e2e/egresspolicy/egresspolicy_test.go

Update check eip

---

pkg/coalescing/coalescing.go
pkg/iptables/interface.go
pkg/lock/lock.go
pkg/utils/set/set.go

更新依赖开源代码更全面的信息：
* origin link
* changes

Add origin link and changes of vendor code

---

pkg/controller/egress_cluster_info.go

fix egressClusterInfo update with latest resourceVersion

fix egressClusterInfo update with latest resourceVersion

---

pkg/controller/egress_cluster_info.go

fix egci nodeip repet

---

cmd/nettools/client/main.go
cmd/nettools/client/usage.md
cmd/nettools/initFlag.go
test/e2e/common/eip.go
test/e2e/egresspolicy/egresspolicy_test.go

fix e2e error, add retry check eip func

add eip retry func

---

test/e2e/common/egressclusterinfo.go
test/e2e/common/node.go

fix e2e func GetAllNodesIP

---

test/e2e/common/egressclusterinfo.go
test/e2e/egressclusterinfo/egressclusterinfo_test.go

optimise check egci fields

---

pkg/iptables/table.go

Fix https://github.com/spidernet-io/egressgateway/issues/608

Update iptables logs

---

test/Makefile
test/e2e/common/constant.go
test/e2e/common/kwok.go
test/scripts/installKwok.sh

e2e test install kwok

---

go.mod
test/Makefile
test/e2e/common/constant.go
test/e2e/common/egressgateway.go
test/e2e/common/eip.go
test/e2e/common/marshal.go
test/e2e/common/node.go
test/e2e/common/pod.go
test/e2e/reliability/reliability_suite_test.go
test/e2e/reliability/reliability_test.go

e2e R00005: test eip drift after node shut down

e2e R00005: test eip drift after node shut down

---

test/e2e/egresspolicy/egresspolicy_suite_test.go
test/e2e/reliability/reliability_suite_test.go
test/e2e/reliability/reliability_test.go

Fix https://github.com/spidernet-io/egressgateway/issues/631

Fix cannot query module due to -mod=vendor in ci

---

test/e2e/common/egressgateway.go
test/e2e/egressgateway/egressgateway_suite_test.go
test/e2e/egressgateway/egressgateway_test.go
test/e2e/tools/tools.go

e2e G00005, create `egressgateway` using empty `DefaultEIP`

[E2E] G00005, create `egressgateway` using empty `DefaultEIP`

---

test/scripts/installKwok.sh

add retry when install kwok

---

test/doc/egressclusterinfo.md
test/doc/egressclusterinfo_zh.md

#673 
update e2e testcase doc for egressClusterInfo

[e2e doc] update e2e testcase doc for egressClusterInfo

---

.github/workflows/build-image-base.yaml
.github/workflows/call-release-image.yaml
cmd/nettools/client/main.go
cmd/nettools/server/main.go

ref https://github.com/spidernet-io/egressgateway/issues/653 https://github.com/spidernet-io/egressgateway/issues/649
* 增加新的构建产物（⚠️ 要注意在我们 github action 的 token 赋予新的镜像推送权限）
* ghcr.io/spidernet-io/egressgateway-nettools-base
* ghcr.io/spidernet-io/egressgateway-nettools
* 支持 http 测试端点，方便用户 Demo 测试
* `/ws` 为 websocket 的端点
*  `/` 则为 http 测测试端点
* 更新 get started 文档（PR 合并后）
* 增加一个新的部署 chart（PR 合并后）
* 增加一个 YAML 部署示例（PR 合并后）

Add workflow for nettool image

---

pkg/agent/police.go

ref https://github.com/spidernet-io/egressgateway/issues/655 对 EgressGateway 下发的规则增加注释，便于排查问题，追踪流量策略。
```log
Chain EGRESSGATEWAY-MARK-REQUEST (1 references)
pkts bytes target     prot opt in     out     source               destination
0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* egw:rqYfjkfKrT6nGSGk */ /* Set mark for EgressPolicy cluster-policy */ match-set egress-src-v4-aea5445f32d3ff6d9 src ! match-set egress-cluster-cidr-ipv4 dst ctdir ORIGINAL MARK set 0x26bd9373
0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* egw:NSVcK7GJ0pgR6zyw */ /* Set mark for EgressPolicy default-ns-policy */ match-set egress-src-v4-4e931d24857afe3cf src ! match-set egress-cluster-cidr-ipv4 dst ctdir ORIGINAL MARK set …
```

Update iptables comments

---

Makefile.defs
test/Makefile
test/scripts/installKwok.sh

[e2e] fix install kwok

---

.github/workflows/call-e2e.yaml

Update call-e2e.yaml for test

---

test/e2e/egresspolicy/egresspolicy_test.go

pending test case EgressPolicy

[test-debug] pending test case EgressPolicy

---

.github/workflows/call-release-changelog.yaml
.github/workflows/call-release-pages.yaml

The code incorporated in the pr #729 needs to be optimized.

[docs]: optimize doc version for egressgateway

---

pkg/controller/egress_cluster_info/egress_cluster_info.go

fix failed update egci status
issue: #773
问题分析：
reconcileEgressClusterInfo 方法 会更新 egci 状态
如果 egci CRD Spec 中 PodCidrMode 为 calico，我们会开启一个协程检测 集群是否有 calico 资源
如果协程检测到 calico 资源，协程会 (1) 设置 controller watch calico ippools 资源，(2) 并进行 egci status 的更新
因为是协程工作，当协程在设置 controller watch calico ippools 成功之后，在 egci status 更新之前，有 calico ippools 资源更新
这样会进入 reconcileEgressClusterInfo方法，更新 egci status，但是  reconcileEgressClusterInfo 主线程中，
并没有 更新  Status.PodCIDR 的逻辑，所以在  reconcileEgressClusterInfo 方法中 updateEgressClusterInfo， 会有之前旧数据残留
具体现象：
当用例将 Spec.AutoDetect.PodCidrMode 由 k8s 改为 calico 时，由于以上原因，协程的 update 在 reconcileEgressClusterInfo update 操作后，就会有 k8s 相关 cidr 残留，导致报错。
解决方法：
在 reconcileEgressClusterInfo 中加入了 清除旧数据及更新 status 的逻辑

fix failed update egci status

---

pkg/controller/egress_cluster_info/egress_cluster_info.go

cancel get egci when update

---

test/Makefile

fix https://github.com/spidernet-io/egressgateway/issues/664

Clean image

---

pkg/controller/egress_cluster_info/egress_cluster_info.go

it is not nessisery init egressClusterInfo in Renconcile，
because Reconcile is triggered by Egci events

cancel initEgci in Reconcile

---

.github/workflows/auto-pr-ci.yaml
.github/workflows/call-e2e.yaml
Makefile.defs
README.md
docs/README.en.md
docs/README.zh.md
docs/mkdocs.yml
docs/usage/Install.zh.md
test/Makefile
test/scripts/installFlannel.sh
test/scripts/installWeave.sh
test/yaml/testpod.yaml

https://github.com/spidernet-io/egressgateway/issues/648

Add weave and flannel

---

test/scripts/installCalico.sh

fix install calico failed when install-kind step
issue is #845

add retry curl in installCalico.sh

---

pkg/controller/webhook/mutating_test.go
pkg/controller/webhook/validate_test.go

添加 webhook 中 有关 validate 及 mutating 的单元测试

add ut about updateEgressClusterPolicy for the file validate.go

---

test/e2e/egresspolicy/egresspolicy_test.go

用例：P00018 P00019	
用例用来验证 policy 不允许编辑的字段 Spec.EgressIP.IP 和 Spec.EgressGatewayName
我们期望 这两个字段被编辑时，会被拒绝

Add test case P00018 P00019

---

.github/workflows/auto-nightly-ci.yaml

Add k8s version v1.28.0 in workflow

---

.github/workflows/netlify.yml

如果 `docs/**` 路径的文档发生**变更**，则自动构建部署一个**文档站**到 Netlify。每个 PR 之间也不会覆盖。Netlify 是免费的，默认保留 60 天。
效果可以参考 https://github.com/lou-lan/ttt/pull/6

Add Netlify

---

.github/ISSUE_TEMPLATE/bug.md

Fix the spelling mistakes

---

test/e2e/common/beforeeach.go
test/e2e/common/egp.go
test/e2e/common/egw.go
test/e2e/common/pod.go
test/e2e/egressgateway/egressgateway_test.go
test/e2e/reliability/reliability_test.go

修复 e2e 用例中 gateway name 重复问题
Fix: #881

Fix the repetition of gateway name in e2e test

---

test/e2e/common/pool.go

修复 test/e2e/common/pool.go 中 GenIPPools 函数，参数 num 问题。
加了 num 不能小于 1 的限制
Fix: #923

Fix the validation of the parameter  in function GenIPPools

---

pkg/agent/police.go
pkg/controller/cluster_endpoint_slice.go

Fix the issue of abnormal deletion of ipset and the problem of cluster_endpoint_slice not synchronizing podIP

Fix the issue of abnormal deletion of ipset 

---

pkg/egressgateway/egress_gateway_webhook.go

Fix https://github.com/spidernet-io/egressgateway/issues/581

Update the webhook validation process for egressgateway

---

pkg/egressgateway/egress_gateway_webhook.go

Fix https://github.com/spidernet-io/egressgateway/issues/837

Update validation of egress gateway

---

.github/workflows/call-release-pages.yaml

Support publishing development documents.

Publish development documents through github actions.

---

docs/usage/Install.en.md
docs/usage/Install.zh.md

1.set chainInsertMode--命令行错误
2.为应用创建 EgressPolicy CR 对象失败--更改ymal
3.给节点打 label，nodename为变量，增加一步先查看node

fix install bug

---

docs/concepts/Datapath.zh.md

docs: format datapath.zh.md

---

docs/usage/Install.en.md
docs/usage/Install.zh.md

Fix the status of the egressgateway in the installation documents

---

pkg/egressgateway/egress_gateway.go

fix: https://github.com/spidernet-io/egressgateway/issues/852

fix: incorrect policy reassignment caused by egt

---

pkg/egressgateway/egress_gateway_webhook.go
test/e2e/egresspolicy/egresspolicy_test.go

Fix https://github.com/spidernet-io/egressgateway/issues/876

Fix update egress gateway

---

test/e2e/egresspolicy/egresspolicy_test.go

Fix https://github.com/spidernet-io/egressgateway/issues/971

Increase pod waiting time from 5 seconds to 10 seconds

---

pkg/controller/webhook/validate.go
test/e2e/egresspolicy/egresspolicy_test.go

Fix: https://github.com/spidernet-io/egressgateway/issues/893

Update pending test

---

pkg/egressgateway/egress_gateway.go

Fix: #984
修复 ipv6 单栈，policy rr 模式下，IP 重复分配问题

Fix IP repetition when testing IPv6 allocation

---

pkg/controller/webhook/validate.go
pkg/egressgateway/egress_gateway.go
test/e2e/reliability/reliability_ip_test.go

Fix #973: open the test case R00008
Fix #983

open the test case R00008

---

cmd/controller/cmd/clean.go

Fix https://github.com/spidernet-io/egressgateway/issues/1004

Fix residual CR when uninstall egressgateway

---

pkg/controller/egress_tunnel.go
pkg/k8s/apis/v1beta1/egresstunnel_types.go

Fix https://github.com/spidernet-io/egressgateway/issues/897
```
0s          Normal    StatusChanged             egresstunnel/workstation2                            EgressTunnel status changes to HeartbeatTimeout.
```

Add event for egress tunnel status changed

---

.github/workflows/call-release-pages.yaml

Supports publishing rc versions of docs to dev

Supports publishing rc versions of docs to dev

---

pkg/controller/webhook/validate.go

Fix https://github.com/spidernet-io/egressgateway/issues/1036

Fix check eip in dual stack

---

pkg/egressgateway/egress_gateway_webhook.go

Fix https://github.com/spidernet-io/egressgateway/issues/1039

Fix check for duplicate EgressGateway

---

Makefile.defs
test/Makefile
test/e2e/common/check_eip.go
test/e2e/common/egw.go
test/e2e/common/node.go
test/e2e/common/pod.go
test/e2e/reliability/reliability_suite_test.go
test/e2e/reliability/reliability_test.go
test/e2e/tools/tools.go

update test case R00005

---

.github/workflows/auto-release.yaml
.github/workflows/build-image-base.yaml
.github/workflows/call-e2e.yaml
.github/workflows/call-release-changelog.yaml
.github/workflows/call-release-chart.yaml
.github/workflows/call-release-image.yaml
.github/workflows/call-release-pages.yaml
.github/workflows/call-trivy.yaml
.github/workflows/helm.yml
.github/workflows/lint-golang.yaml
.github/workflows/lint-yaml.yaml

Change download-artifact from v4.0.0 to v3.0.2
Change upload-artifact from v4.0.0 to v3.1.3
Looks there are some problem with upload-artifact v4.0.0, as:
https://github.com/actions/download-artifact/issues/249

Change upload-artifact from v4.0.0 to v3.1.3

---

test/e2e/egressendpointslice/egressendpointslice_test.go

cancel to delete egressEndpointSlice manually in case S00001

---

test/e2e/egressendpointslice/egressendpointslice_test.go
test/e2e/egressgateway/egressgateway_test.go
test/e2e/egresspolicy/egresspolicy_test.go
test/e2e/reliability/reliability_test.go

Fix duplicate gateway ip in some test case
Fix #1163 
Fix #1164
Fix #1165

fix duplicate gateway ip in some test case

---

test/e2e/reliability/reliability_ip_test.go

Add ip number check in R00008

---

pkg/controller/egress_cluster_info/egress_cluster_info_test.go

Fix https://github.com/spidernet-io/egressgateway/issues/1184
Fix gomonkey patch in `for range`, the reason is `defer` func not run.

Fix gomonkey patch in `for range`

---

charts/templates/daemonset.yaml

Fix https://github.com/spidernet-io/egressgateway/issues/1191

Fix helm render values of agent pyroscope server addr

---

test/e2e/reliability/reliability_ip_test.go

Fix https://github.com/spidernet-io/egressgateway/issues/1196

fix time out to wait egressgateway status to be empty after delete the polices

---

.github/workflows/auto-cherrypick.yaml

automatically port the label from the initial cherry-picked PR

---

pkg/egressgateway/egress_gateway.go

Fix https://github.com/spidernet-io/egressgateway/issues/1246

Fix create egress gateway when allocate policy empty

---

test/Makefile

Fix make e2e_init clean all exist images.

Fix make clean effort for e2e_init

---

pkg/agent/police.go

Fix https://github.com/spidernet-io/egressgateway/issues/1278

Fix not mangle policy insertion priority 

---

pkg/controller/webhook/validate.go
pkg/controller/webhook/validate_test.go
pkg/egressgateway/egress_gateway.go
pkg/utils/ip/ip.go

When create egw, if it is not match any thing, it is will not update usage status.
Fix #1309

Fix first egw create not update usage

---

.github/codespell-ignorewords
.github/workflows/auto-nightly-ci.yaml

CI: Added compatibility test for K8s 1.30

CI: Added compatibility test for K8s 1.30

---

pkg/controller/webhook/validate.go
pkg/iptables/restore_buffer.go
pkg/iptables/testutils/test.go
test/e2e/common/ds.go
test/e2e/common/egw.go

Fix https://github.com/spidernet-io/egressgateway/issues/1439
Fix https://github.com/spidernet-io/egressgateway/issues/1438

Fix golanglint

---

test/scripts/installCalico.sh

Fix https://github.com/spidernet-io/egressgateway/actions/runs/11618996631

Update Calico installation script to support v3.29.0

---

pkg/controller/webhook/validate.go
pkg/controller/webhook/validate_test.go
pkg/egressgateway/egress_gateway.go

Fix https://github.com/spidernet-io/egressgateway/issues/1574
**Describe:**
Fix create multi ipv4 policy use one egress got validate error #1575

Fix create multi policy use one egress got validate error

---

pkg/agent/police.go
test/e2e/egresspolicy/egresspolicy_test.go

Fix: https://github.com/spidernet-io/egressgateway/issues/1536

Fix IPv6 egressgateway not work in enable IPv4/IPv6 dual stack

---

.golangci.yaml

Update .golangci.yml to properly configure the skip-dirs field
Fix https://github.com/spidernet-io/egressgateway/issues/1630

Update .golangci.yml to properly configure the skip-dirs field
